baseURL: https://jerome-adriaens.github.io
title: Jérôme Adriaens
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true
pagination:
  pagerSize: 20

taxonomies:
    tag: tags
    
enableEmoji: true

menu:
    main:
        - name: Papers
          url: papers/
          weight: 2
        - name: Courses
          url: courses/
          weight: 3

params:
    description: "This website hosts Jérôme Adriaens's research papers, books, course materials, data, curriculum vitae, and contact information."
    author: Jérôme Adriaens
    # googleAnalyticsID: "G-XXXXX"
    DateFormat: "January 2006"
    defaultTheme: light
    hideFooter: false
    disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowAllPagesInArchive: false
    MainSections: ["courses","papers"]
    ShowToc: false
    disableScrollToTop: true
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true
    profileMode:
          enabled: true
          title: Jérôme Adriaens
          subtitle: "I am a **PhD student** in the neuroengineering laboratory from University of Liège working on the integration of neuroscience and robotics. My work currently focuses on the incorporation of **neuromodulation** within neural network based **dimensionality reduction**."
          imageUrl: "picture.jpeg"
          imageWidth: 160
          imageHeight: 160
          buttons:
            - name: Publications
              url: papers/
            - name: Courses
              url: courses/

    socialIcons:
        - name: CV
          url: cv.pdf
        - name: Email
          url: mailto:jadriaens@uliege.be
        - name: Google Scholar
          url: https://scholar.google.com/citations?user=OL0FnDAAAAAJ&hl=en
        - name: GitHub
          url: https://github.com/JeromeAdriaens
        - name: Location
          url: location/
        - name : LinkedIn
          url : https://www.linkedin.com/in/j%C3%A9r%C3%B4me-adriaens-14ab8b14a
        - name: Bluesky
          url: https://bsky.app/profile/jeromeadriaens.bsky.social

    assets:
        disableScrollBarStyle: true
    cover:
        hiddenInList: false
        hiddenInSingle: true
    label:
      text: "Jérôme Adriaens"
      icon: favicon.ico
      iconHeight: 18

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: autumn 
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2
